### ISSUE TITLE
测试时报错 AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Aochca** [zombie12138/nuaa_check_action#1]
感谢大佬的懒人打卡神器~(￣▽￣)~*  小白按照使用方法设置了想要打卡偷个懒但是在测试过程中报错了
报错代码如下
![image](https://user-images.githubusercontent.com/45527420/105183162-cf71cc00-5b68-11eb-8a8a-38e2d8acf8f7.png)
Secret设置与例子相同，仅修改了用户名、密码和经纬度等
检查过多次用户名和密码以及尝试登陆都确认无误 然后重试仍然报错 搜索了一下应该是[没有匹配到元素导致的](https://blog.csdn.net/hongyiWeng/article/details/99823437) 是因为配置的学号中含有字母导致匹配不了吗？麻烦请大佬帮忙看看是什么问题呀 谢谢！

**Comment by zombie12138** [comment]
这个是登陆失败了QAQ，uid只有登陆之后才能返回，所以正则表达式找不到UID。如果排除了账号密码填错，最可能你是研究生所以登陆的协议不相同吧，由于我也没有研究生的账户，建议你可以本地调试一下login或者Fiddler抓个包看一看登陆的过程然后修改login函数owo。

**Comment by qrzbing** [comment]
我今天试了一下，遇到和你相同的错误。解决方法是先打一次卡，之后就能搜到了。
