### ISSUE TITLE
貌似最新一次commit之后发信部分出了问题

### ISSUE THREAD

**Issue by splendidwrx** [zombie12138/nuaa_check_action#3]
貌似最新一次commit之后发信部分出了问题，没法正常发送邮件。
严格按json格式填了信息之后，并测试之后，action成功运行，但邮件推送中没有发信记录

**Comment by zombie12138** [comment]
如果显示发送成功，并且发信箱也有但是没收到，可能是因为163向qq邮箱发会发不出去。
如果发送邮件过程中产生异常可能是邮箱登录失败或者发送信箱填写错误。
还有很小的几率qq没有推送邮件，这个一年也就一两次。

另外我看你显示登录成功了但是没有获取到uid，可能是因为你的uid不一样？
你可以进入校外打卡的网页，f12搜索uid可以查到自己的uid，有可能格式不一样？或者本地调试一下获取id uid的代码。
实在不行get id uid 都返回个随机数字也行（心大一点），据我以往经验，i南航大概的确不会校验这两个数字。

**Comment by zombie12138** [comment]
之前有同学反映先网页打一次卡就能得到uid了，可以尝试一下😂

**Comment by splendidwrx** [comment]
多谢，我尝试一下

**Comment by splendidwrx** [comment]
多次尝试获取都不成功，于是我抓了一下，uid是一个八位数，ID是个四位数，直接生成随机数喂进去了（光速逃 
明天看看能不能打上。

**Comment by zombie12138** [comment]
hhhh，真奇怪，有人还登录不上，你登录上得不到uid，如果找到解决欢迎贡献代码。。。我之前校内打卡我没仔细看数据包，室友直接用的我的uid，打卡的id也一直没换，也没出问题😂
