### ISSUE TITLE
话说是不是可以减少一部分 post 的数据

### ISSUE THREAD

**Issue by qrzbing** [zombie12138/nuaa_check_action#4]
今天抓了一下包发现 post 的数据好像只需要这些：

```
sfzhux: 0
zhuxdz: 
szgj: 
szcs: 
szgjcs: 
sfjwfh: 0
sfyjsjwfh: 0
sfjcjwfh: 0
sflznjcjwfh: 0
sflqjkm: 4
jkmys: 1
sfjtgfxdq: 0
tw: 3
sfcxtz: 0
sfjcbh: 0
sfcxzysx: 0
qksm: 
sfyyjc: 0
jcjgqr: 0
remark: 
address: xxxx
area: xxxxx
province: xxxx
city: xxxx
sfzx: 0
sfjcwhry: 0
sfjchbry: 0
sfcyglq: 0
gllx: 
glksrq: 
jcbhlx: 
jcbhrq: 
ismoved: 0
bztcyy: 
sftjhb: 0
sftjwh: 0
sftjwz: 0
sfjcwzry: 0
jcjg: 
```

好像不需要 id 和 uid 的样子？

而如果之前出现了 uid/id，系统中就会保存这两项，导致以后 get 的时候都能找到，而实际上似乎是不需要的。。

**Comment by zombie12138** [comment]
应该可以吧，但我抓的确实一直都是代码里面那么多数据。id是每次打卡时候给的，好像每次都不一样。uid是自己的用户id，应该不会变。i南航不管这两个数。
![IMG_20210205_004656](https://user-images.githubusercontent.com/17005226/106926628-3d62e980-674c-11eb-9f6f-6578e2259605.jpg)

**Comment by qrzbing** [comment]
可以换个没有uid的账号抓，实际上好像确实不管uid（
这里也是提出一个建议，天知道学校那帮人咋写的代码。。
